name: Github
targets:
  Github:
    type: framework
    platform: iOS
    deploymentTarget: "10.0"
    sources: [Github]
    info:
      path: ./Info.plist
      version: 1.1.4
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    
