//
// ActionsRepositoryPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ActionsRepositoryPermissions: Codable {

    /** Whether GitHub Actions is enabled on the repository. */
    public var enabled: Bool
    public var allowedActions: AllowedActions
    /** The API URL to use to get or set the actions that are allowed to run, when &#x60;allowed_actions&#x60; is set to &#x60;selected&#x60;. */
    public var selectedActionsUrl: String?

    public init(enabled: Bool, allowedActions: AllowedActions, selectedActionsUrl: String? = nil) {
        self.enabled = enabled
        self.allowedActions = allowedActions
        self.selectedActionsUrl = selectedActionsUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case enabled
        case allowedActions = "allowed_actions"
        case selectedActionsUrl = "selected_actions_url"
    }

}

