//
// Actor.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Actor */
public struct Actor: Codable {

    public var id: Int
    public var login: String
    public var displayLogin: String?
    public var gravatarId: String?
    public var url: String
    public var avatarUrl: String

    public init(id: Int, login: String, displayLogin: String? = nil, gravatarId: String?, url: String, avatarUrl: String) {
        self.id = id
        self.login = login
        self.displayLogin = displayLogin
        self.gravatarId = gravatarId
        self.url = url
        self.avatarUrl = avatarUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case login
        case displayLogin = "display_login"
        case gravatarId = "gravatar_id"
        case url
        case avatarUrl = "avatar_url"
    }

}

