//
// AllowedActions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The permissions policy that controls the actions that are allowed to run. Can be one of: &#x60;all&#x60;, &#x60;local_only&#x60;, or &#x60;selected&#x60;. */
public enum AllowedActions: String, Codable, CaseIterable {
    case all = "all"
    case localOnly = "local_only"
    case selected = "selected"
}
