//
// Announcement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Enterprise global announcement */
public struct Announcement: Codable {

    /** The announcement text in GitHub Flavored Markdown. For more information about GitHub Flavored Markdown, see \&quot;[Mastering markdown](https://guides.github.com/features/mastering-markdown/).\&quot; */
    public var announcement: String
    /** The time at which the announcement expires. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: &#x60;YYYY-MM-DDTHH:MM:SSZ&#x60;. To set an announcement that never expires, omit this parameter, set it to &#x60;null&#x60;, or set it to an empty string. */
    public var expiresAt: String?

    public init(announcement: String, expiresAt: String? = nil) {
        self.announcement = announcement
        self.expiresAt = expiresAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case announcement
        case expiresAt = "expires_at"
    }

}

