//
// AuthenticationToken.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Authentication Token */
public struct AuthenticationToken: Codable {

    public enum RepositorySelection: String, Codable, CaseIterable {
        case all = "all"
        case selected = "selected"
    }
    /** The token used for authentication */
    public var token: String
    /** The time this token expires */
    public var expiresAt: Date
    public var permissions: String?
    /** The repositories this token has access to */
    public var repositories: [Repository]?
    public var singleFile: String?
    /** Describe whether all repositories have been selected or there&#39;s a selection involved */
    public var repositorySelection: RepositorySelection?

    public init(token: String, expiresAt: Date, permissions: String? = nil, repositories: [Repository]? = nil, singleFile: String? = nil, repositorySelection: RepositorySelection? = nil) {
        self.token = token
        self.expiresAt = expiresAt
        self.permissions = permissions
        self.repositories = repositories
        self.singleFile = singleFile
        self.repositorySelection = repositorySelection
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case token
        case expiresAt = "expires_at"
        case permissions
        case repositories
        case singleFile = "single_file"
        case repositorySelection = "repository_selection"
    }

}

