//
// Blob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Blob */
public struct Blob: Codable {

    public var content: String
    public var encoding: String
    public var url: String
    public var sha: String
    public var size: Int?
    public var nodeId: String
    public var highlightedContent: String?

    public init(content: String, encoding: String, url: String, sha: String, size: Int?, nodeId: String, highlightedContent: String? = nil) {
        self.content = content
        self.encoding = encoding
        self.url = url
        self.sha = sha
        self.size = size
        self.nodeId = nodeId
        self.highlightedContent = highlightedContent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case content
        case encoding
        case url
        case sha
        case size
        case nodeId = "node_id"
        case highlightedContent = "highlighted_content"
    }

}

