//
// BranchProtection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Branch Protection */
public struct BranchProtection: Codable {

    public var url: String?
    public var requiredStatusChecks: BranchProtectionRequiredStatusChecks
    public var enforceAdmins: ProtectedBranchAdminEnforced?
    public var requiredPullRequestReviews: ProtectedBranchPullRequestReview?
    public var restrictions: BranchRestrictionPolicy?
    public var requiredLinearHistory: BranchProtectionRequiredLinearHistory?
    public var allowForcePushes: BranchProtectionRequiredLinearHistory?
    public var allowDeletions: BranchProtectionRequiredLinearHistory?
    public var enabled: Bool
    public var name: String?
    public var protectionUrl: String?

    public init(url: String? = nil, requiredStatusChecks: BranchProtectionRequiredStatusChecks, enforceAdmins: ProtectedBranchAdminEnforced? = nil, requiredPullRequestReviews: ProtectedBranchPullRequestReview? = nil, restrictions: BranchRestrictionPolicy? = nil, requiredLinearHistory: BranchProtectionRequiredLinearHistory? = nil, allowForcePushes: BranchProtectionRequiredLinearHistory? = nil, allowDeletions: BranchProtectionRequiredLinearHistory? = nil, enabled: Bool, name: String? = nil, protectionUrl: String? = nil) {
        self.url = url
        self.requiredStatusChecks = requiredStatusChecks
        self.enforceAdmins = enforceAdmins
        self.requiredPullRequestReviews = requiredPullRequestReviews
        self.restrictions = restrictions
        self.requiredLinearHistory = requiredLinearHistory
        self.allowForcePushes = allowForcePushes
        self.allowDeletions = allowDeletions
        self.enabled = enabled
        self.name = name
        self.protectionUrl = protectionUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case requiredStatusChecks = "required_status_checks"
        case enforceAdmins = "enforce_admins"
        case requiredPullRequestReviews = "required_pull_request_reviews"
        case restrictions
        case requiredLinearHistory = "required_linear_history"
        case allowForcePushes = "allow_force_pushes"
        case allowDeletions = "allow_deletions"
        case enabled
        case name
        case protectionUrl = "protection_url"
    }

}

