//
// BranchWithProtection.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Branch With Protection */
public struct BranchWithProtection: Codable {

    public var name: String
    public var commit: Commit
    public var links: BranchWithProtectionLinks
    public var protected: Bool
    public var protection: BranchProtection
    public var protectionUrl: String
    public var pattern: String?
    public var requiredApprovingReviewCount: Int?

    public init(name: String, commit: Commit, links: BranchWithProtectionLinks, protected: Bool, protection: BranchProtection, protectionUrl: String, pattern: String? = nil, requiredApprovingReviewCount: Int? = nil) {
        self.name = name
        self.commit = commit
        self.links = links
        self.protected = protected
        self.protection = protection
        self.protectionUrl = protectionUrl
        self.pattern = pattern
        self.requiredApprovingReviewCount = requiredApprovingReviewCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case commit
        case links = "_links"
        case protected
        case protection
        case protectionUrl = "protection_url"
        case pattern
        case requiredApprovingReviewCount = "required_approving_review_count"
    }

}

