//
// BranchRestrictionPolicyPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BranchRestrictionPolicyPermissions: Codable {

    public var metadata: String?
    public var contents: String?
    public var issues: String?
    public var singleFile: String?

    public init(metadata: String? = nil, contents: String? = nil, issues: String? = nil, singleFile: String? = nil) {
        self.metadata = metadata
        self.contents = contents
        self.issues = issues
        self.singleFile = singleFile
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case metadata
        case contents
        case issues
        case singleFile = "single_file"
    }

}

