//
// BranchRestrictionPolicyApps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BranchRestrictionPolicyApps: Codable {

    public var id: Int?
    public var slug: String?
    public var nodeId: String?
    public var owner: BranchRestrictionPolicyOwner?
    public var name: String?
    public var description: String?
    public var externalUrl: String?
    public var htmlUrl: String?
    public var createdAt: String?
    public var updatedAt: String?
    public var permissions: BranchRestrictionPolicyPermissions?
    public var events: [String]?

    public init(id: Int? = nil, slug: String? = nil, nodeId: String? = nil, owner: BranchRestrictionPolicyOwner? = nil, name: String? = nil, description: String? = nil, externalUrl: String? = nil, htmlUrl: String? = nil, createdAt: String? = nil, updatedAt: String? = nil, permissions: BranchRestrictionPolicyPermissions? = nil, events: [String]? = nil) {
        self.id = id
        self.slug = slug
        self.nodeId = nodeId
        self.owner = owner
        self.name = name
        self.description = description
        self.externalUrl = externalUrl
        self.htmlUrl = htmlUrl
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.permissions = permissions
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case slug
        case nodeId = "node_id"
        case owner
        case name
        case description
        case externalUrl = "external_url"
        case htmlUrl = "html_url"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case permissions
        case events
    }

}

