//
// BranchProtectionRequiredStatusChecks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct BranchProtectionRequiredStatusChecks: Codable {

    public var url: String?
    public var enforcementLevel: String
    public var contexts: [String]
    public var contextsUrl: String?

    public init(url: String? = nil, enforcementLevel: String, contexts: [String], contextsUrl: String? = nil) {
        self.url = url
        self.enforcementLevel = enforcementLevel
        self.contexts = contexts
        self.contextsUrl = contextsUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case enforcementLevel = "enforcement_level"
        case contexts
        case contextsUrl = "contexts_url"
    }

}

