//
// CheckSuitePreferencePreferencesAutoTriggerChecks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CheckSuitePreferencePreferencesAutoTriggerChecks: Codable {

    public var appId: Int
    public var setting: Bool

    public init(appId: Int, setting: Bool) {
        self.appId = appId
        self.setting = setting
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case appId = "app_id"
        case setting
    }

}

