//
// CollaboratorPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CollaboratorPermissions: Codable {

    public var pull: Bool
    public var push: Bool
    public var admin: Bool

    public init(pull: Bool, push: Bool, admin: Bool) {
        self.pull = pull
        self.push = push
        self.admin = admin
    }

}

