//
// CommitSearchResultItemCommit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CommitSearchResultItemCommit: Codable {

    public var author: CommitSearchResultItemCommitAuthor
    public var committer: GitUser?
    public var commentCount: Int
    public var message: String
    public var tree: ShortBranchCommit
    public var url: String
    public var verification: Verification?

    public init(author: CommitSearchResultItemCommitAuthor, committer: GitUser?, commentCount: Int, message: String, tree: ShortBranchCommit, url: String, verification: Verification? = nil) {
        self.author = author
        self.committer = committer
        self.commentCount = commentCount
        self.message = message
        self.tree = tree
        self.url = url
        self.verification = verification
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case author
        case committer
        case commentCount = "comment_count"
        case message
        case tree
        case url
        case verification
    }

}

