//
// CommitCommitTree.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CommitCommitTree: Codable {

    public var sha: String
    public var url: String

    public init(sha: String, url: String) {
        self.sha = sha
        self.url = url
    }

}

