//
// CommitFiles.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CommitFiles: Codable {

    public var filename: String?
    public var additions: Int?
    public var deletions: Int?
    public var changes: Int?
    public var status: String?
    public var rawUrl: String?
    public var blobUrl: String?
    public var patch: String?
    public var sha: String?
    public var contentsUrl: String?
    public var previousFilename: String?

    public init(filename: String? = nil, additions: Int? = nil, deletions: Int? = nil, changes: Int? = nil, status: String? = nil, rawUrl: String? = nil, blobUrl: String? = nil, patch: String? = nil, sha: String? = nil, contentsUrl: String? = nil, previousFilename: String? = nil) {
        self.filename = filename
        self.additions = additions
        self.deletions = deletions
        self.changes = changes
        self.status = status
        self.rawUrl = rawUrl
        self.blobUrl = blobUrl
        self.patch = patch
        self.sha = sha
        self.contentsUrl = contentsUrl
        self.previousFilename = previousFilename
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case filename
        case additions
        case deletions
        case changes
        case status
        case rawUrl = "raw_url"
        case blobUrl = "blob_url"
        case patch
        case sha
        case contentsUrl = "contents_url"
        case previousFilename = "previous_filename"
    }

}

