//
// ConfigurationStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ConfigurationStatus: Codable {

    public var status: String?
    public var progress: [ConfigurationStatusProgress]?

    public init(status: String? = nil, progress: [ConfigurationStatusProgress]? = nil) {
        self.status = status
        self.progress = progress
    }

}

