//
// ContentFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Content File */
public struct ContentFile: Codable {

    public var type: String
    public var encoding: String
    public var size: Int
    public var name: String
    public var path: String
    public var content: String
    public var sha: String
    public var url: String
    public var gitUrl: String?
    public var htmlUrl: String?
    public var downloadUrl: String?
    public var links: ContentTreeLinks
    public var target: String?
    public var submoduleGitUrl: String?

    public init(type: String, encoding: String, size: Int, name: String, path: String, content: String, sha: String, url: String, gitUrl: String?, htmlUrl: String?, downloadUrl: String?, links: ContentTreeLinks, target: String? = nil, submoduleGitUrl: String? = nil) {
        self.type = type
        self.encoding = encoding
        self.size = size
        self.name = name
        self.path = path
        self.content = content
        self.sha = sha
        self.url = url
        self.gitUrl = gitUrl
        self.htmlUrl = htmlUrl
        self.downloadUrl = downloadUrl
        self.links = links
        self.target = target
        self.submoduleGitUrl = submoduleGitUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case type
        case encoding
        case size
        case name
        case path
        case content
        case sha
        case url
        case gitUrl = "git_url"
        case htmlUrl = "html_url"
        case downloadUrl = "download_url"
        case links = "_links"
        case target
        case submoduleGitUrl = "submodule_git_url"
    }

}

