//
// ContentReferenceAttachment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Content Reference attachments allow you to provide context around URLs posted in comments */
public struct ContentReferenceAttachment: Codable {

    /** The ID of the attachment */
    public var id: Int
    /** The title of the attachment */
    public var title: String
    /** The body of the attachment */
    public var body: String
    /** The node_id of the content attachment */
    public var nodeId: String?

    public init(id: Int, title: String, body: String, nodeId: String? = nil) {
        self.id = id
        self.title = title
        self.body = body
        self.nodeId = nodeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case title
        case body
        case nodeId = "node_id"
    }

}

