//
// ContributorActivityWeeks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ContributorActivityWeeks: Codable {

    public var w: String?
    public var a: Int?
    public var d: Int?
    public var c: Int?

    public init(w: String? = nil, a: Int? = nil, d: Int? = nil, c: Int? = nil) {
        self.w = w
        self.a = a
        self.d = d
        self.c = c
    }

}

