//
// EnterpriseOverviewRepos.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseOverviewRepos: Codable {

    public var totalRepos: Int?
    public var rootRepos: Int?
    public var forkRepos: Int?
    public var orgRepos: Int?
    public var totalPushes: Int?
    public var totalWikis: Int?

    public init(totalRepos: Int? = nil, rootRepos: Int? = nil, forkRepos: Int? = nil, orgRepos: Int? = nil, totalPushes: Int? = nil, totalWikis: Int? = nil) {
        self.totalRepos = totalRepos
        self.rootRepos = rootRepos
        self.forkRepos = forkRepos
        self.orgRepos = orgRepos
        self.totalPushes = totalPushes
        self.totalWikis = totalWikis
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalRepos = "total_repos"
        case rootRepos = "root_repos"
        case forkRepos = "fork_repos"
        case orgRepos = "org_repos"
        case totalPushes = "total_pushes"
        case totalWikis = "total_wikis"
    }

}

