//
// EnterpriseSettingsEnterpriseSmtp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseSettingsEnterpriseSmtp: Codable {

    public var enabled: Bool?
    public var address: String?
    public var authentication: String?
    public var port: String?
    public var domain: String?
    public var username: String?
    public var userName: String?
    public var enableStarttlsAuto: Bool?
    public var password: String?
    public var discardToNoreplyAddress: Bool?
    public var supportAddress: String?
    public var supportAddressType: String?
    public var noreplyAddress: String?

    public init(enabled: Bool? = nil, address: String? = nil, authentication: String? = nil, port: String? = nil, domain: String? = nil, username: String? = nil, userName: String? = nil, enableStarttlsAuto: Bool? = nil, password: String? = nil, discardToNoreplyAddress: Bool? = nil, supportAddress: String? = nil, supportAddressType: String? = nil, noreplyAddress: String? = nil) {
        self.enabled = enabled
        self.address = address
        self.authentication = authentication
        self.port = port
        self.domain = domain
        self.username = username
        self.userName = userName
        self.enableStarttlsAuto = enableStarttlsAuto
        self.password = password
        self.discardToNoreplyAddress = discardToNoreplyAddress
        self.supportAddress = supportAddress
        self.supportAddressType = supportAddressType
        self.noreplyAddress = noreplyAddress
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case enabled
        case address
        case authentication
        case port
        case domain
        case username
        case userName = "user_name"
        case enableStarttlsAuto = "enable_starttls_auto"
        case password
        case discardToNoreplyAddress = "discard-to-noreply-address"
        case supportAddress = "support_address"
        case supportAddressType = "support_address_type"
        case noreplyAddress = "noreply_address"
    }

}

