//
// EnterpriseSettingsEnterpriseGithubSsl.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseSettingsEnterpriseGithubSsl: Codable {

    public var enabled: Bool?
    public var cert: String?
    public var key: String?

    public init(enabled: Bool? = nil, cert: String? = nil, key: String? = nil) {
        self.enabled = enabled
        self.cert = cert
        self.key = key
    }

}

