//
// Enterprise.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An enterprise account */
public struct Enterprise: Codable {

    /** A short description of the enterprise. */
    public var description: String?
    public var htmlUrl: String
    /** The enterprise&#39;s website URL. */
    public var websiteUrl: String?
    /** Unique identifier of the enterprise */
    public var id: Int
    public var nodeId: String
    /** The name of the enterprise. */
    public var name: String
    /** The slug url identifier for the enterprise. */
    public var slug: String
    public var createdAt: Date?
    public var updatedAt: Date?
    public var avatarUrl: String

    public init(description: String? = nil, htmlUrl: String, websiteUrl: String? = nil, id: Int, nodeId: String, name: String, slug: String, createdAt: Date?, updatedAt: Date?, avatarUrl: String) {
        self.description = description
        self.htmlUrl = htmlUrl
        self.websiteUrl = websiteUrl
        self.id = id
        self.nodeId = nodeId
        self.name = name
        self.slug = slug
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.avatarUrl = avatarUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case description
        case htmlUrl = "html_url"
        case websiteUrl = "website_url"
        case id
        case nodeId = "node_id"
        case name
        case slug
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case avatarUrl = "avatar_url"
    }

}

