//
// EnterpriseSettingsEnterpriseLicense.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseSettingsEnterpriseLicense: Codable {

    public var seats: Int?
    public var evaluation: Bool?
    public var perpetual: Bool?
    public var unlimitedSeating: Bool?
    public var supportKey: String?
    public var sshAllowed: Bool?
    public var clusterSupport: Bool?
    public var expireAt: String?

    public init(seats: Int? = nil, evaluation: Bool? = nil, perpetual: Bool? = nil, unlimitedSeating: Bool? = nil, supportKey: String? = nil, sshAllowed: Bool? = nil, clusterSupport: Bool? = nil, expireAt: String? = nil) {
        self.seats = seats
        self.evaluation = evaluation
        self.perpetual = perpetual
        self.unlimitedSeating = unlimitedSeating
        self.supportKey = supportKey
        self.sshAllowed = sshAllowed
        self.clusterSupport = clusterSupport
        self.expireAt = expireAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case seats
        case evaluation
        case perpetual
        case unlimitedSeating = "unlimited_seating"
        case supportKey = "support_key"
        case sshAllowed = "ssh_allowed"
        case clusterSupport = "cluster_support"
        case expireAt = "expire_at"
    }

}

