//
// EnterpriseSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseSettings: Codable {

    public var enterprise: EnterpriseSettingsEnterprise?
    public var runList: [String]?

    public init(enterprise: EnterpriseSettingsEnterprise? = nil, runList: [String]? = nil) {
        self.enterprise = enterprise
        self.runList = runList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case enterprise
        case runList = "run_list"
    }

}

