//
// EnterpriseOverviewGists.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseOverviewGists: Codable {

    public var totalGists: Int?
    public var privateGists: Int?
    public var publicGists: Int?

    public init(totalGists: Int? = nil, privateGists: Int? = nil, publicGists: Int? = nil) {
        self.totalGists = totalGists
        self.privateGists = privateGists
        self.publicGists = publicGists
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalGists = "total_gists"
        case privateGists = "private_gists"
        case publicGists = "public_gists"
    }

}

