//
// EnterpriseSettingsEnterpriseAvatar.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseSettingsEnterpriseAvatar: Codable {

    public var enabled: Bool?
    public var uri: String?

    public init(enabled: Bool? = nil, uri: String? = nil) {
        self.enabled = enabled
        self.uri = uri
    }

}

