//
// EnterpriseOverview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseOverview: Codable {

    public var repos: EnterpriseOverviewRepos?
    public var hooks: EnterpriseOverviewHooks?
    public var pages: EnterpriseOverviewPages?
    public var orgs: EnterpriseOverviewOrgs?
    public var users: EnterpriseOverviewUsers?
    public var pulls: EnterpriseOverviewPulls?
    public var issues: EnterpriseOverviewIssues?
    public var milestones: EnterpriseOverviewMilestones?
    public var gists: EnterpriseOverviewGists?
    public var comments: EnterpriseOverviewComments?

    public init(repos: EnterpriseOverviewRepos? = nil, hooks: EnterpriseOverviewHooks? = nil, pages: EnterpriseOverviewPages? = nil, orgs: EnterpriseOverviewOrgs? = nil, users: EnterpriseOverviewUsers? = nil, pulls: EnterpriseOverviewPulls? = nil, issues: EnterpriseOverviewIssues? = nil, milestones: EnterpriseOverviewMilestones? = nil, gists: EnterpriseOverviewGists? = nil, comments: EnterpriseOverviewComments? = nil) {
        self.repos = repos
        self.hooks = hooks
        self.pages = pages
        self.orgs = orgs
        self.users = users
        self.pulls = pulls
        self.issues = issues
        self.milestones = milestones
        self.gists = gists
        self.comments = comments
    }

}

