//
// EnterpriseOverviewHooks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseOverviewHooks: Codable {

    public var totalHooks: Int?
    public var activeHooks: Int?
    public var inactiveHooks: Int?

    public init(totalHooks: Int? = nil, activeHooks: Int? = nil, inactiveHooks: Int? = nil) {
        self.totalHooks = totalHooks
        self.activeHooks = activeHooks
        self.inactiveHooks = inactiveHooks
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalHooks = "total_hooks"
        case activeHooks = "active_hooks"
        case inactiveHooks = "inactive_hooks"
    }

}

