//
// EnterpriseSettingsEnterpriseSnmp.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EnterpriseSettingsEnterpriseSnmp: Codable {

    public var enabled: Bool?
    public var community: String?

    public init(enabled: Bool? = nil, community: String? = nil) {
        self.enabled = enabled
        self.community = community
    }

}

