//
// EventRepo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct EventRepo: Codable {

    public var id: Int
    public var name: String
    public var url: String

    public init(id: Int, name: String, url: String) {
        self.id = id
        self.name = name
        self.url = url
    }

}

