//
// Feed.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Feed */
public struct Feed: Codable {

    public var timelineUrl: String
    public var userUrl: String
    public var currentUserPublicUrl: String?
    public var currentUserUrl: String?
    public var currentUserActorUrl: String?
    public var currentUserOrganizationUrl: String?
    public var currentUserOrganizationUrls: [String]?
    public var links: FeedLinks

    public init(timelineUrl: String, userUrl: String, currentUserPublicUrl: String? = nil, currentUserUrl: String? = nil, currentUserActorUrl: String? = nil, currentUserOrganizationUrl: String? = nil, currentUserOrganizationUrls: [String]? = nil, links: FeedLinks) {
        self.timelineUrl = timelineUrl
        self.userUrl = userUrl
        self.currentUserPublicUrl = currentUserPublicUrl
        self.currentUserUrl = currentUserUrl
        self.currentUserActorUrl = currentUserActorUrl
        self.currentUserOrganizationUrl = currentUserOrganizationUrl
        self.currentUserOrganizationUrls = currentUserOrganizationUrls
        self.links = links
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case timelineUrl = "timeline_url"
        case userUrl = "user_url"
        case currentUserPublicUrl = "current_user_public_url"
        case currentUserUrl = "current_user_url"
        case currentUserActorUrl = "current_user_actor_url"
        case currentUserOrganizationUrl = "current_user_organization_url"
        case currentUserOrganizationUrls = "current_user_organization_urls"
        case links = "_links"
    }

}

