//
// FileCommitCommitTree.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FileCommitCommitTree: Codable {

    public var url: String?
    public var sha: String?

    public init(url: String? = nil, sha: String? = nil) {
        self.url = url
        self.sha = sha
    }

}

