//
// FileCommitCommitParents.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FileCommitCommitParents: Codable {

    public var url: String?
    public var htmlUrl: String?
    public var sha: String?

    public init(url: String? = nil, htmlUrl: String? = nil, sha: String? = nil) {
        self.url = url
        self.htmlUrl = htmlUrl
        self.sha = sha
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case htmlUrl = "html_url"
        case sha
    }

}

