//
// FullRepositoryPermissions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct FullRepositoryPermissions: Codable {

    public var admin: Bool
    public var pull: Bool
    public var push: Bool

    public init(admin: Bool, pull: Bool, push: Bool) {
        self.admin = admin
        self.pull = pull
        self.push = push
    }

}

