//
// GistsFiles.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GistsFiles: Codable {

    /** Content of the file */
    public var content: String

    public init(content: String) {
        self.content = content
    }

}

