//
// GitCommitTree.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GitCommitTree: Codable {

    /** SHA for the commit */
    public var sha: String
    public var url: String

    public init(sha: String, url: String) {
        self.sha = sha
        self.url = url
    }

}

