//
// GitUser.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Metaproperties for Git author/committer information. */
public struct GitUser: Codable {

    public var name: String?
    public var email: String?
    public var date: String?

    public init(name: String? = nil, email: String? = nil, date: String? = nil) {
        self.name = name
        self.email = email
        self.date = date
    }

}

