//
// GlobalHookConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GlobalHookConfig: Codable {

    public var url: String?
    public var contentType: String?
    public var insecureSsl: String?
    public var secret: String?

    public init(url: String? = nil, contentType: String? = nil, insecureSsl: String? = nil, secret: String? = nil) {
        self.url = url
        self.contentType = contentType
        self.insecureSsl = insecureSsl
        self.secret = secret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case contentType = "content_type"
        case insecureSsl = "insecure_ssl"
        case secret
    }

}

