//
// GpgKeySubkeys.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GpgKeySubkeys: Codable {

    public var id: Int?
    public var primaryKeyId: Int?
    public var keyId: String?
    public var publicKey: String?
    public var emails: [Any]?
    public var subkeys: [Any]?
    public var canSign: Bool?
    public var canEncryptComms: Bool?
    public var canEncryptStorage: Bool?
    public var canCertify: Bool?
    public var createdAt: String?
    public var expiresAt: String?
    public var rawKey: String?

    public init(id: Int? = nil, primaryKeyId: Int? = nil, keyId: String? = nil, publicKey: String? = nil, emails: [Any]? = nil, subkeys: [Any]? = nil, canSign: Bool? = nil, canEncryptComms: Bool? = nil, canEncryptStorage: Bool? = nil, canCertify: Bool? = nil, createdAt: String? = nil, expiresAt: String? = nil, rawKey: String? = nil) {
        self.id = id
        self.primaryKeyId = primaryKeyId
        self.keyId = keyId
        self.publicKey = publicKey
        self.emails = emails
        self.subkeys = subkeys
        self.canSign = canSign
        self.canEncryptComms = canEncryptComms
        self.canEncryptStorage = canEncryptStorage
        self.canCertify = canCertify
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.rawKey = rawKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case primaryKeyId = "primary_key_id"
        case keyId = "key_id"
        case publicKey = "public_key"
        case emails
        case subkeys
        case canSign = "can_sign"
        case canEncryptComms = "can_encrypt_comms"
        case canEncryptStorage = "can_encrypt_storage"
        case canCertify = "can_certify"
        case createdAt = "created_at"
        case expiresAt = "expires_at"
        case rawKey = "raw_key"
    }

}

