//
// Hook.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Webhooks for repositories. */
public struct Hook: Codable {

    public var type: String
    /** Unique identifier of the webhook. */
    public var id: Int
    /** The name of a valid service, use &#39;web&#39; for a webhook. */
    public var name: String
    /** Determines whether the hook is actually triggered on pushes. */
    public var active: Bool
    /** Determines what events the hook is triggered for. Default: [&#39;push&#39;]. */
    public var events: [String]
    public var config: HookConfig
    public var updatedAt: Date
    public var createdAt: Date
    public var url: String
    public var testUrl: String
    public var pingUrl: String
    public var lastResponse: HookResponse

    public init(type: String, id: Int, name: String, active: Bool, events: [String], config: HookConfig, updatedAt: Date, createdAt: Date, url: String, testUrl: String, pingUrl: String, lastResponse: HookResponse) {
        self.type = type
        self.id = id
        self.name = name
        self.active = active
        self.events = events
        self.config = config
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.url = url
        self.testUrl = testUrl
        self.pingUrl = pingUrl
        self.lastResponse = lastResponse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case type
        case id
        case name
        case active
        case events
        case config
        case updatedAt = "updated_at"
        case createdAt = "created_at"
        case url
        case testUrl = "test_url"
        case pingUrl = "ping_url"
        case lastResponse = "last_response"
    }

}

