//
// Hovercard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Hovercard */
public struct Hovercard: Codable {

    public var contexts: [HovercardContexts]

    public init(contexts: [HovercardContexts]) {
        self.contexts = contexts
    }

}

