//
// HovercardContexts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct HovercardContexts: Codable {

    public var message: String
    public var octicon: String

    public init(message: String, octicon: String) {
        self.message = message
        self.octicon = octicon
    }

}

