//
// InlineObject115.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject115: Codable {

    /** The contents of the comment. */
    public var body: String

    public init(body: String) {
        self.body = body
    }

}

