//
// InlineResponse20014.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20014: Codable {

    public var totalCount: Int
    public var jobs: [Job]

    public init(totalCount: Int, jobs: [Job]) {
        self.totalCount = totalCount
        self.jobs = jobs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case jobs
    }

}

