//
// InlineObject65.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject65: Codable {

    /** The position of the card in a column */
    public var position: String
    /** The unique identifier of the column the card should be moved to */
    public var columnId: Int?

    public init(position: String, columnId: Int? = nil) {
        self.position = position
        self.columnId = columnId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case position
        case columnId = "column_id"
    }

}

