//
// InlineResponse2004.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2004: Codable {

    public var totalCount: Double?
    public var runners: [Runner]?

    public init(totalCount: Double? = nil, runners: [Runner]? = nil) {
        self.totalCount = totalCount
        self.runners = runners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case runners
    }

}

