//
// InlineObject132.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject132: Codable {

    /** Specify a custom domain for the repository. Sending a &#x60;null&#x60; value will remove the custom domain. For more about custom domains, see \&quot;[Using a custom domain with GitHub Pages](https://help.github.com/articles/using-a-custom-domain-with-github-pages/).\&quot; */
    public var cname: String?
    /** Configures access controls for the GitHub Pages site. If public is set to &#x60;true&#x60;, the site is accessible to anyone on the internet. If set to &#x60;false&#x60;, the site will only be accessible to users who have at least &#x60;read&#x60; access to the repository that published the site. This includes anyone in your Enterprise if the repository is set to &#x60;internal&#x60; visibility. This feature is only available to repositories in an organization on an Enterprise plan. */
    public var _public: Bool?
    public var source: String

    public init(cname: String? = nil, _public: Bool? = nil, source: String) {
        self.cname = cname
        self._public = _public
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case cname
        case _public = "public"
        case source
    }

}

