//
// InlineObject42.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject42: Codable {

    /** List of repository IDs that can access the runner group. */
    public var selectedRepositoryIds: [Int]

    public init(selectedRepositoryIds: [Int]) {
        self.selectedRepositoryIds = selectedRepositoryIds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case selectedRepositoryIds = "selected_repository_ids"
    }

}

