//
// InlineObject32.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject32: Codable {

    /** The comment text. */
    public var body: String

    public init(body: String) {
        self.body = body
    }

}

