//
// InlineObject10.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject10: Codable {

    /** The user&#39;s username. */
    public var login: String
    /** **Required for built-in authentication.** The user&#39;s email address. This parameter can be omitted when using CAS, LDAP, or SAML. For details on built-in and centrally-managed authentication, see the the [GitHub authentication guide](https://help.github.com/enterprise/2.18/admin/guides/user-management/authenticating-users-for-your-github-enterprise-server-instance/). */
    public var email: String?

    public init(login: String, email: String? = nil) {
        self.login = login
        self.email = email
    }

}

