//
// InlineResponse20012.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20012: Codable {

    public var totalCount: Int
    public var artifacts: [Artifact]

    public init(totalCount: Int, artifacts: [Artifact]) {
        self.totalCount = totalCount
        self.artifacts = artifacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case artifacts
    }

}

