//
// InlineObject154.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject154: Codable {

    /** Determines if notifications should be received from this repository. */
    public var subscribed: Bool?
    /** Determines if all notifications should be blocked from this repository. */
    public var ignored: Bool?

    public init(subscribed: Bool? = nil, ignored: Bool? = nil) {
        self.subscribed = subscribed
        self.ignored = ignored
    }

}

