//
// InlineObject134.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject134: Codable {

    /** The state of enforcement for the hook on this repository. */
    public var enforcement: String?

    public init(enforcement: String? = nil) {
        self.enforcement = enforcement
    }

}

