//
// InlineResponse403Block.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse403Block: Codable {

    public var reason: String?
    public var createdAt: String?
    public var htmlUrl: String?

    public init(reason: String? = nil, createdAt: String? = nil, htmlUrl: String? = nil) {
        self.reason = reason
        self.createdAt = createdAt
        self.htmlUrl = htmlUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case reason
        case createdAt = "created_at"
        case htmlUrl = "html_url"
    }

}

