//
// InlineObject122.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject122: Codable {

    /** The name of the label to add to the issue. Must contain at least one label. **Note:** Alternatively, you can pass a single label as a &#x60;string&#x60; or an &#x60;array&#x60; of labels directly, but GitHub recommends passing an object with the &#x60;labels&#x60; key. */
    public var labels: [String]

    public init(labels: [String]) {
        self.labels = labels
    }

}

