//
// InlineObject54.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject54: Codable {

    public enum Privacy: String, Codable, CaseIterable {
        case secret = "secret"
        case closed = "closed"
    }
    public enum Permission: String, Codable, CaseIterable {
        case pull = "pull"
        case push = "push"
        case admin = "admin"
    }
    /** The name of the team. */
    public var name: String
    /** The description of the team. */
    public var description: String?
    /** The level of privacy this team should have. Editing teams without specifying this parameter leaves &#x60;privacy&#x60; intact. When a team is nested, the &#x60;privacy&#x60; for parent teams cannot be &#x60;secret&#x60;. The options are:   **For a non-nested team:**   \\* &#x60;secret&#x60; - only visible to organization owners and members of this team.   \\* &#x60;closed&#x60; - visible to all members of this organization.   **For a parent or child team:**   \\* &#x60;closed&#x60; - visible to all members of this organization. */
    public var privacy: Privacy?
    /** **Deprecated**. The permission that new repositories will be added to the team with when none is specified. Can be one of:   \\* &#x60;pull&#x60; - team members can pull, but not push to or administer newly-added repositories.   \\* &#x60;push&#x60; - team members can pull and push, but not administer newly-added repositories.   \\* &#x60;admin&#x60; - team members can pull, push and administer newly-added repositories. */
    public var permission: Permission? = .pull
    /** The ID of a team to set as the parent team. */
    public var parentTeamId: Int?

    public init(name: String, description: String? = nil, privacy: Privacy? = nil, permission: Permission? = .pull, parentTeamId: Int? = nil) {
        self.name = name
        self.description = description
        self.privacy = privacy
        self.permission = permission
        self.parentTeamId = parentTeamId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case description
        case privacy
        case permission
        case parentTeamId = "parent_team_id"
    }

}

