//
// InlineResponse20018.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20018: Codable {

    public var totalCount: Int
    public var checkSuites: [CheckSuite]

    public init(totalCount: Int, checkSuites: [CheckSuite]) {
        self.totalCount = totalCount
        self.checkSuites = checkSuites
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case checkSuites = "check_suites"
    }

}

