//
// InlineResponse2005.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2005: Codable {

    public var totalCount: Int
    public var repositories: [Repository]
    public var repositorySelection: String?

    public init(totalCount: Int, repositories: [Repository], repositorySelection: String? = nil) {
        self.totalCount = totalCount
        self.repositories = repositories
        self.repositorySelection = repositorySelection
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case repositories
        case repositorySelection = "repository_selection"
    }

}

