//
// InlineObject47.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject47: Codable {

    public var config: OrgsOrgHooksHookIdConfig?
    /** Determines what [events](https://docs.github.com/enterprise-server@3.0/webhooks/event-payloads) the hook is triggered for. */
    public var events: [String]?
    /** Determines if notifications are sent when the webhook is triggered. Set to &#x60;true&#x60; to send notifications. */
    public var active: Bool? = true
    public var name: String?

    public init(config: OrgsOrgHooksHookIdConfig? = nil, events: [String]? = nil, active: Bool? = true, name: String? = nil) {
        self.config = config
        self.events = events
        self.active = active
        self.name = name
    }

}

