//
// InlineObject98.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject98: Codable {

    /** The commit message. */
    public var message: String
    /** The new file content, using Base64 encoding. */
    public var content: String
    /** **Required if you are updating a file**. The blob SHA of the file being replaced. */
    public var sha: String?
    /** The branch name. Default: the repository’s default branch (usually &#x60;master&#x60;) */
    public var branch: String?
    public var committer: ReposOwnerRepoContentsPathCommitter?
    public var author: ReposOwnerRepoContentsPathAuthor?

    public init(message: String, content: String, sha: String? = nil, branch: String? = nil, committer: ReposOwnerRepoContentsPathCommitter? = nil, author: ReposOwnerRepoContentsPathAuthor? = nil) {
        self.message = message
        self.content = content
        self.sha = sha
        self.branch = branch
        self.committer = committer
        self.author = author
    }

}

