//
// InlineObject5.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject5: Codable {

    /** The organization&#39;s new name. */
    public var login: String

    public init(login: String) {
        self.login = login
    }

}

