//
// InlineResponse2008.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2008: Codable {

    public var totalCount: Int
    public var runners: [Runner]

    public init(totalCount: Int, runners: [Runner]) {
        self.totalCount = totalCount
        self.runners = runners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case runners
    }

}

