//
// InlineResponse20013.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20013: Codable {

    public var totalCount: Int
    public var workflowRuns: [WorkflowRun]

    public init(totalCount: Int, workflowRuns: [WorkflowRun]) {
        self.totalCount = totalCount
        self.workflowRuns = workflowRuns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case workflowRuns = "workflow_runs"
    }

}

