//
// InlineObject57.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject57: Codable {

    /** The discussion comment&#39;s body text. */
    public var body: String

    public init(body: String) {
        self.body = body
    }

}

