//
// InlineObject15.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject15: Codable {

    /** The OAuth access token used to authenticate to the GitHub API. */
    public var accessToken: String?

    public init(accessToken: String? = nil) {
        self.accessToken = accessToken
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case accessToken = "access_token"
    }

}

