//
// InlineObject74.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject74: Codable {

    /** The git reference for the workflow. The reference can be a branch or tag name. */
    public var ref: String
    /** Input keys and values configured in the workflow file. The maximum number of properties is 10. Any default properties configured in the workflow file will be used when &#x60;inputs&#x60; are omitted. */
    public var inputs: [String:String]?

    public init(ref: String, inputs: [String:String]? = nil) {
        self.ref = ref
        self.inputs = inputs
    }

}

