//
// InlineResponse415.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse415: Codable {

    public var message: String
    public var documentationUrl: String

    public init(message: String, documentationUrl: String) {
        self.message = message
        self.documentationUrl = documentationUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case message
        case documentationUrl = "documentation_url"
    }

}

