//
// InlineObject69.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject69: Codable {

    public enum Permission: String, Codable, CaseIterable {
        case read = "read"
        case write = "write"
        case admin = "admin"
    }
    /** The permission to grant the collaborator. */
    public var permission: Permission? = .write

    public init(permission: Permission? = .write) {
        self.permission = permission
    }

}

