//
// InlineObject145.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject145: Codable {

    public enum Event: String, Codable, CaseIterable {
        case approve = "APPROVE"
        case requestChanges = "REQUEST_CHANGES"
        case comment = "COMMENT"
    }
    /** The SHA of the commit that needs a review. Not using the latest commit SHA may render your review comment outdated if a subsequent commit modifies the line you specify as the &#x60;position&#x60;. Defaults to the most recent commit in the pull request when you do not specify a value. */
    public var commitId: String?
    /** **Required** when using &#x60;REQUEST_CHANGES&#x60; or &#x60;COMMENT&#x60; for the &#x60;event&#x60; parameter. The body text of the pull request review. */
    public var body: String?
    /** The review action you want to perform. The review actions include: &#x60;APPROVE&#x60;, &#x60;REQUEST_CHANGES&#x60;, or &#x60;COMMENT&#x60;. By leaving this blank, you set the review action state to &#x60;PENDING&#x60;, which means you will need to [submit the pull request review](https://docs.github.com/enterprise-server@3.0/rest/reference/pulls#submit-a-review-for-a-pull-request) when you are ready. */
    public var event: Event?
    /** Use the following table to specify the location, destination, and contents of the draft review comment. */
    public var comments: [ReposOwnerRepoPullsPullNumberReviewsComments]?

    public init(commitId: String? = nil, body: String? = nil, event: Event? = nil, comments: [ReposOwnerRepoPullsPullNumberReviewsComments]? = nil) {
        self.commitId = commitId
        self.body = body
        self.event = event
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case commitId = "commit_id"
        case body
        case event
        case comments
    }

}

