//
// InlineResponse2002.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse2002: Codable {

    public var totalCount: Double
    public var runnerGroups: [RunnerGroupsEnterprise]

    public init(totalCount: Double, runnerGroups: [RunnerGroupsEnterprise]) {
        self.totalCount = totalCount
        self.runnerGroups = runnerGroups
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case runnerGroups = "runner_groups"
    }

}

