//
// InlineObject139.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject139: Codable {

    public enum State: String, Codable, CaseIterable {
        case _open = "open"
        case closed = "closed"
    }
    /** The title of the pull request. */
    public var title: String?
    /** The contents of the pull request. */
    public var body: String?
    /** State of this Pull Request. Either &#x60;open&#x60; or &#x60;closed&#x60;. */
    public var state: State?
    /** The name of the branch you want your changes pulled into. This should be an existing branch on the current repository. You cannot update the base branch on a pull request to point to another repository. */
    public var base: String?
    /** Indicates whether [maintainers can modify](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/) the pull request. */
    public var maintainerCanModify: Bool?

    public init(title: String? = nil, body: String? = nil, state: State? = nil, base: String? = nil, maintainerCanModify: Bool? = nil) {
        self.title = title
        self.body = body
        self.state = state
        self.base = base
        self.maintainerCanModify = maintainerCanModify
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case title
        case body
        case state
        case base
        case maintainerCanModify = "maintainer_can_modify"
    }

}

