//
// InlineObject133.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The source branch and directory used to publish your Pages site. */
public struct InlineObject133: Codable {

    public var source: ReposOwnerRepoPagesSource

    public init(source: ReposOwnerRepoPagesSource) {
        self.source = source
    }

}

