//
// InlineResponse20017.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineResponse20017: Codable {

    public var totalCount: Int
    public var checkRuns: [CheckRun]

    public init(totalCount: Int, checkRuns: [CheckRun]) {
        self.totalCount = totalCount
        self.checkRuns = checkRuns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case totalCount = "total_count"
        case checkRuns = "check_runs"
    }

}

