//
// InlineObject40.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject40: Codable {

    public enum Visibility: String, Codable, CaseIterable {
        case selected = "selected"
        case all = "all"
        case _private = "private"
    }
    /** Name of the runner group. */
    public var name: String
    /** Visibility of a runner group. You can select all repositories, select individual repositories, or limit access to private repositories. Can be one of: &#x60;all&#x60;, &#x60;selected&#x60;, or &#x60;private&#x60;. */
    public var visibility: Visibility? = .all
    /** List of repository IDs that can access the runner group. */
    public var selectedRepositoryIds: [Int]?
    /** List of runner IDs to add to the runner group. */
    public var runners: [Int]?

    public init(name: String, visibility: Visibility? = .all, selectedRepositoryIds: [Int]? = nil, runners: [Int]? = nil) {
        self.name = name
        self.visibility = visibility
        self.selectedRepositoryIds = selectedRepositoryIds
        self.runners = runners
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case visibility
        case selectedRepositoryIds = "selected_repository_ids"
        case runners
    }

}

