//
// InlineObject78.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject78: Codable {

    /** contexts parameter */
    public var contexts: [String]

    public init(contexts: [String]) {
        self.contexts = contexts
    }

}

