//
// InlineObject163.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject163: Codable {

    /** The content of your new _.ghl_ license file. */
    public var license: String?

    public init(license: String? = nil) {
        self.license = license
    }

}

