//
// InlineObject77.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject77: Codable {

    /** Require branches to be up to date before merging. */
    public var strict: Bool?
    /** The list of status checks to require in order to merge into this branch */
    public var contexts: [String]?

    public init(strict: Bool? = nil, contexts: [String]? = nil) {
        self.strict = strict
        self.contexts = contexts
    }

}

