//
// InlineObject169.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject169: Codable {

    public enum Content: String, Codable, CaseIterable {
        case plusOne = "+1"
        case minusOne = "-1"
        case laugh = "laugh"
        case confused = "confused"
        case heart = "heart"
        case hooray = "hooray"
        case rocket = "rocket"
        case eyes = "eyes"
    }
    /** The [reaction type](https://docs.github.com/enterprise-server@3.0/rest/reference/reactions#reaction-types) to add to the team discussion comment. */
    public var content: Content

    public init(content: Content) {
        self.content = content
    }

}

