//
// InlineObject101.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject101: Codable {

    public enum State: String, Codable, CaseIterable {
        case error = "error"
        case failure = "failure"
        case inactive = "inactive"
        case inProgress = "in_progress"
        case queued = "queued"
        case pending = "pending"
        case success = "success"
    }
    public enum Environment: String, Codable, CaseIterable {
        case production = "production"
        case staging = "staging"
        case qa = "qa"
    }
    /** The state of the status. Can be one of &#x60;error&#x60;, &#x60;failure&#x60;, &#x60;inactive&#x60;, &#x60;in_progress&#x60;, &#x60;queued&#x60; &#x60;pending&#x60;, or &#x60;success&#x60;. **Note:** To use the &#x60;inactive&#x60; state, you must provide the [&#x60;application/vnd.github.ant-man-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#enhanced-deployments) custom media type. To use the &#x60;in_progress&#x60; and &#x60;queued&#x60; states, you must provide the [&#x60;application/vnd.github.flash-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#deployment-statuses) custom media type. When you set a transient deployment to &#x60;inactive&#x60;, the deployment will be shown as &#x60;destroyed&#x60; in GitHub. */
    public var state: State
    /** The target URL to associate with this status. This URL should contain output to keep the user updated while the task is running or serve as historical information for what happened in the deployment. **Note:** It&#39;s recommended to use the &#x60;log_url&#x60; parameter, which replaces &#x60;target_url&#x60;. */
    public var targetUrl: String? = ""
    /** The full URL of the deployment&#39;s output. This parameter replaces &#x60;target_url&#x60;. We will continue to accept &#x60;target_url&#x60; to support legacy uses, but we recommend replacing &#x60;target_url&#x60; with &#x60;log_url&#x60;. Setting &#x60;log_url&#x60; will automatically set &#x60;target_url&#x60; to the same value. Default: &#x60;\&quot;\&quot;&#x60;   **Note:** This parameter requires you to use the [&#x60;application/vnd.github.ant-man-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#enhanced-deployments) custom media type. **Note:** This parameter requires you to use the [&#x60;application/vnd.github.ant-man-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#enhanced-deployments) custom media type. */
    public var logUrl: String? = ""
    /** A short description of the status. The maximum description length is 140 characters. */
    public var description: String? = ""
    /** Name for the target deployment environment, which can be changed when setting a deploy status. For example, &#x60;production&#x60;, &#x60;staging&#x60;, or &#x60;qa&#x60;. **Note:** This parameter requires you to use the [&#x60;application/vnd.github.flash-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#deployment-statuses) custom media type. */
    public var environment: Environment?
    /** Sets the URL for accessing your environment. Default: &#x60;\&quot;\&quot;&#x60;   **Note:** This parameter requires you to use the [&#x60;application/vnd.github.ant-man-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#enhanced-deployments) custom media type. **Note:** This parameter requires you to use the [&#x60;application/vnd.github.ant-man-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#enhanced-deployments) custom media type. */
    public var environmentUrl: String? = ""
    /** Adds a new &#x60;inactive&#x60; status to all prior non-transient, non-production environment deployments with the same repository and &#x60;environment&#x60; name as the created status&#39;s deployment. An &#x60;inactive&#x60; status is only added to deployments that had a &#x60;success&#x60; state. Default: &#x60;true&#x60;   **Note:** To add an &#x60;inactive&#x60; status to &#x60;production&#x60; environments, you must use the [&#x60;application/vnd.github.flash-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#deployment-statuses) custom media type.   **Note:** This parameter requires you to use the [&#x60;application/vnd.github.ant-man-preview+json&#x60;](https://docs.github.com/enterprise-server@3.0/rest/overview/api-previews#enhanced-deployments) custom media type. */
    public var autoInactive: Bool?

    public init(state: State, targetUrl: String? = "", logUrl: String? = "", description: String? = "", environment: Environment? = nil, environmentUrl: String? = "", autoInactive: Bool? = nil) {
        self.state = state
        self.targetUrl = targetUrl
        self.logUrl = logUrl
        self.description = description
        self.environment = environment
        self.environmentUrl = environmentUrl
        self.autoInactive = autoInactive
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case state
        case targetUrl = "target_url"
        case logUrl = "log_url"
        case description
        case environment
        case environmentUrl = "environment_url"
        case autoInactive = "auto_inactive"
    }

}

