//
// InlineObject46.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject46: Codable {

    /** Must be passed as \&quot;web\&quot;. */
    public var name: String
    public var config: OrgsOrgHooksConfig
    /** Determines what [events](https://docs.github.com/enterprise-server@3.0/webhooks/event-payloads) the hook is triggered for. */
    public var events: [String]?
    /** Determines if notifications are sent when the webhook is triggered. Set to &#x60;true&#x60; to send notifications. */
    public var active: Bool? = true

    public init(name: String, config: OrgsOrgHooksConfig, events: [String]? = nil, active: Bool? = true) {
        self.name = name
        self.config = config
        self.events = events
        self.active = active
    }

}

