//
// InlineObject41.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject41: Codable {

    public enum Visibility: String, Codable, CaseIterable {
        case selected = "selected"
        case all = "all"
        case _private = "private"
    }
    /** Name of the runner group. */
    public var name: String?
    /** Visibility of a runner group. You can select all repositories, select individual repositories, or all private repositories. Can be one of: &#x60;all&#x60;, &#x60;selected&#x60;, or &#x60;private&#x60;. */
    public var visibility: Visibility?

    public init(name: String? = nil, visibility: Visibility? = nil) {
        self.name = name
        self.visibility = visibility
    }

}

