//
// InlineObject135.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject135: Codable {

    /** The name of the project. */
    public var name: String
    /** The description of the project. */
    public var body: String?

    public init(name: String, body: String? = nil) {
        self.name = name
        self.body = body
    }

}

