//
// InlineObject4.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject4: Codable {

    /** The organization&#39;s username. */
    public var login: String
    /** The login of the user who will manage this organization. */
    public var admin: String
    /** The organization&#39;s display name. */
    public var profileName: String?

    public init(login: String, admin: String, profileName: String? = nil) {
        self.login = login
        self.admin = admin
        self.profileName = profileName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case login
        case admin
        case profileName = "profile_name"
    }

}

