//
// InlineObject92.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject92: Codable {

    public var state: CodeScanningAlertSetState
    public var dismissedReason: CodeScanningAlertDismissedReason?

    public init(state: CodeScanningAlertSetState, dismissedReason: CodeScanningAlertDismissedReason? = nil) {
        self.state = state
        self.dismissedReason = dismissedReason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case state
        case dismissedReason = "dismissed_reason"
    }

}

