//
// InlineObject23.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject23: Codable {

    /** A list of scopes that this authorization is in. */
    public var scopes: [String]?
    /** A list of scopes to add to this authorization. */
    public var addScopes: [String]?
    /** A list of scopes to remove from this authorization. */
    public var removeScopes: [String]?
    /** A note to remind you what the OAuth token is for. */
    public var note: String?
    /** A URL to remind you what app the OAuth token is for. */
    public var noteUrl: String?
    /** A unique string to distinguish an authorization from others created for the same client ID and user. */
    public var fingerprint: String?

    public init(scopes: [String]? = nil, addScopes: [String]? = nil, removeScopes: [String]? = nil, note: String? = nil, noteUrl: String? = nil, fingerprint: String? = nil) {
        self.scopes = scopes
        self.addScopes = addScopes
        self.removeScopes = removeScopes
        self.note = note
        self.noteUrl = noteUrl
        self.fingerprint = fingerprint
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case scopes
        case addScopes = "add_scopes"
        case removeScopes = "remove_scopes"
        case note
        case noteUrl = "note_url"
        case fingerprint
    }

}

