//
// InlineObject175.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InlineObject175: Codable {

    /** A GPG key in ASCII-armored format. */
    public var armoredPublicKey: String

    public init(armoredPublicKey: String) {
        self.armoredPublicKey = armoredPublicKey
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case armoredPublicKey = "armored_public_key"
    }

}

