//
// IssueEventForIssue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Issue Event for Issue */
public struct IssueEventForIssue: Codable {

    public var id: Int?
    public var nodeId: String?
    public var url: String?
    public var actor: SimpleUser?
    public var event: String?
    public var commitId: String?
    public var commitUrl: String?
    public var createdAt: String?
    public var sha: String?
    public var htmlUrl: String?
    public var message: String?
    public var issueUrl: String?
    public var updatedAt: String?
    public var authorAssociation: AuthorAssociation?
    public var body: String?
    public var lockReason: String?
    public var submittedAt: String?
    public var state: String?
    public var pullRequestUrl: String?
    public var bodyHtml: String?
    public var bodyText: String?

    public init(id: Int? = nil, nodeId: String? = nil, url: String? = nil, actor: SimpleUser? = nil, event: String? = nil, commitId: String? = nil, commitUrl: String? = nil, createdAt: String? = nil, sha: String? = nil, htmlUrl: String? = nil, message: String? = nil, issueUrl: String? = nil, updatedAt: String? = nil, authorAssociation: AuthorAssociation? = nil, body: String? = nil, lockReason: String? = nil, submittedAt: String? = nil, state: String? = nil, pullRequestUrl: String? = nil, bodyHtml: String? = nil, bodyText: String? = nil) {
        self.id = id
        self.nodeId = nodeId
        self.url = url
        self.actor = actor
        self.event = event
        self.commitId = commitId
        self.commitUrl = commitUrl
        self.createdAt = createdAt
        self.sha = sha
        self.htmlUrl = htmlUrl
        self.message = message
        self.issueUrl = issueUrl
        self.updatedAt = updatedAt
        self.authorAssociation = authorAssociation
        self.body = body
        self.lockReason = lockReason
        self.submittedAt = submittedAt
        self.state = state
        self.pullRequestUrl = pullRequestUrl
        self.bodyHtml = bodyHtml
        self.bodyText = bodyText
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case nodeId = "node_id"
        case url
        case actor
        case event
        case commitId = "commit_id"
        case commitUrl = "commit_url"
        case createdAt = "created_at"
        case sha
        case htmlUrl = "html_url"
        case message
        case issueUrl = "issue_url"
        case updatedAt = "updated_at"
        case authorAssociation = "author_association"
        case body
        case lockReason = "lock_reason"
        case submittedAt = "submitted_at"
        case state
        case pullRequestUrl = "pull_request_url"
        case bodyHtml = "body_html"
        case bodyText = "body_text"
    }

}

