//
// JobSteps.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct JobSteps: Codable {

    public enum Status: String, Codable, CaseIterable {
        case queued = "queued"
        case inProgress = "in_progress"
        case completed = "completed"
    }
    /** The phase of the lifecycle that the job is currently in. */
    public var status: Status
    /** The outcome of the job. */
    public var conclusion: String?
    /** The name of the job. */
    public var name: String
    public var number: Int
    /** The time that the step started, in ISO 8601 format. */
    public var startedAt: Date?
    /** The time that the job finished, in ISO 8601 format. */
    public var completedAt: Date?

    public init(status: Status, conclusion: String?, name: String, number: Int, startedAt: Date? = nil, completedAt: Date? = nil) {
        self.status = status
        self.conclusion = conclusion
        self.name = name
        self.number = number
        self.startedAt = startedAt
        self.completedAt = completedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case status
        case conclusion
        case name
        case number
        case startedAt = "started_at"
        case completedAt = "completed_at"
    }

}

