//
// KeySimple.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Key Simple */
public struct KeySimple: Codable {

    public var id: Int
    public var key: String

    public init(id: Int, key: String) {
        self.id = id
        self.key = key
    }

}

