//
// LabelSearchResultItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Label Search Result Item */
public struct LabelSearchResultItem: Codable {

    public var id: Int
    public var nodeId: String
    public var url: String
    public var name: String
    public var color: String
    public var _default: Bool
    public var description: String?
    public var score: Int
    public var textMatches: [String]?

    public init(id: Int, nodeId: String, url: String, name: String, color: String, _default: Bool, description: String?, score: Int, textMatches: [String]? = nil) {
        self.id = id
        self.nodeId = nodeId
        self.url = url
        self.name = name
        self.color = color
        self._default = _default
        self.description = description
        self.score = score
        self.textMatches = textMatches
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case nodeId = "node_id"
        case url
        case name
        case color
        case _default = "default"
        case description
        case score
        case textMatches = "text_matches"
    }

}

