//
// Milestone.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A collection of related issues and pull requests. */
public struct Milestone: Codable {

    public enum State: String, Codable, CaseIterable {
        case _open = "open"
        case closed = "closed"
    }
    public var url: String
    public var htmlUrl: String
    public var labelsUrl: String
    public var id: Int
    public var nodeId: String
    /** The number of the milestone. */
    public var number: Int
    /** The state of the milestone. */
    public var state: State = ._open
    /** The title of the milestone. */
    public var title: String
    public var description: String?
    public var creator: SimpleUser?
    public var openIssues: Int
    public var closedIssues: Int
    public var createdAt: Date
    public var updatedAt: Date
    public var closedAt: Date?
    public var dueOn: Date?

    public init(url: String, htmlUrl: String, labelsUrl: String, id: Int, nodeId: String, number: Int, state: State = ._open, title: String, description: String?, creator: SimpleUser?, openIssues: Int, closedIssues: Int, createdAt: Date, updatedAt: Date, closedAt: Date?, dueOn: Date?) {
        self.url = url
        self.htmlUrl = htmlUrl
        self.labelsUrl = labelsUrl
        self.id = id
        self.nodeId = nodeId
        self.number = number
        self.state = state
        self.title = title
        self.description = description
        self.creator = creator
        self.openIssues = openIssues
        self.closedIssues = closedIssues
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.closedAt = closedAt
        self.dueOn = dueOn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case htmlUrl = "html_url"
        case labelsUrl = "labels_url"
        case id
        case nodeId = "node_id"
        case number
        case state
        case title
        case description
        case creator
        case openIssues = "open_issues"
        case closedIssues = "closed_issues"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case closedAt = "closed_at"
        case dueOn = "due_on"
    }

}

