//
// MinimalRepositoryLicense.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct MinimalRepositoryLicense: Codable {

    public var key: String?
    public var name: String?
    public var spdxId: String?
    public var url: String?
    public var nodeId: String?

    public init(key: String? = nil, name: String? = nil, spdxId: String? = nil, url: String? = nil, nodeId: String? = nil) {
        self.key = key
        self.name = name
        self.spdxId = spdxId
        self.url = url
        self.nodeId = nodeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case key
        case name
        case spdxId = "spdx_id"
        case url
        case nodeId = "node_id"
    }

}

