//
// OrganizationSimple.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Organization Simple */
public struct OrganizationSimple: Codable {

    public var login: String
    public var id: Int
    public var nodeId: String
    public var url: String
    public var reposUrl: String
    public var eventsUrl: String
    public var hooksUrl: String
    public var issuesUrl: String
    public var membersUrl: String
    public var publicMembersUrl: String
    public var avatarUrl: String
    public var description: String?

    public init(login: String, id: Int, nodeId: String, url: String, reposUrl: String, eventsUrl: String, hooksUrl: String, issuesUrl: String, membersUrl: String, publicMembersUrl: String, avatarUrl: String, description: String?) {
        self.login = login
        self.id = id
        self.nodeId = nodeId
        self.url = url
        self.reposUrl = reposUrl
        self.eventsUrl = eventsUrl
        self.hooksUrl = hooksUrl
        self.issuesUrl = issuesUrl
        self.membersUrl = membersUrl
        self.publicMembersUrl = publicMembersUrl
        self.avatarUrl = avatarUrl
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case login
        case id
        case nodeId = "node_id"
        case url
        case reposUrl = "repos_url"
        case eventsUrl = "events_url"
        case hooksUrl = "hooks_url"
        case issuesUrl = "issues_url"
        case membersUrl = "members_url"
        case publicMembersUrl = "public_members_url"
        case avatarUrl = "avatar_url"
        case description
    }

}

