//
// PageBuild.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Page Build */
public struct PageBuild: Codable {

    public var url: String
    public var status: String
    public var error: PageBuildError
    public var pusher: SimpleUser?
    public var commit: String
    public var duration: Int
    public var createdAt: Date
    public var updatedAt: Date

    public init(url: String, status: String, error: PageBuildError, pusher: SimpleUser?, commit: String, duration: Int, createdAt: Date, updatedAt: Date) {
        self.url = url
        self.status = status
        self.error = error
        self.pusher = pusher
        self.commit = commit
        self.duration = duration
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case status
        case error
        case pusher
        case commit
        case duration
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

}

