//
// PageBuildError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PageBuildError: Codable {

    public var message: String?

    public init(message: String?) {
        self.message = message
    }

}

