//
// ProjectCard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Project cards represent a scope of work. */
public struct ProjectCard: Codable {

    public var url: String
    /** The project card&#39;s ID */
    public var id: Int
    public var nodeId: String
    public var note: String?
    public var creator: SimpleUser?
    public var createdAt: Date
    public var updatedAt: Date
    /** Whether or not the card is archived */
    public var archived: Bool?
    public var columnUrl: String
    public var contentUrl: String?
    public var projectUrl: String

    public init(url: String, id: Int, nodeId: String, note: String?, creator: SimpleUser?, createdAt: Date, updatedAt: Date, archived: Bool? = nil, columnUrl: String, contentUrl: String? = nil, projectUrl: String) {
        self.url = url
        self.id = id
        self.nodeId = nodeId
        self.note = note
        self.creator = creator
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.archived = archived
        self.columnUrl = columnUrl
        self.contentUrl = contentUrl
        self.projectUrl = projectUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case id
        case nodeId = "node_id"
        case note
        case creator
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case archived
        case columnUrl = "column_url"
        case contentUrl = "content_url"
        case projectUrl = "project_url"
    }

}

