//
// PullRequestMergeResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Pull Request Merge Result */
public struct PullRequestMergeResult: Codable {

    public var sha: String
    public var merged: Bool
    public var message: String

    public init(sha: String, merged: Bool, message: String) {
        self.sha = sha
        self.merged = merged
        self.message = message
    }

}

