//
// PullRequestLabels.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PullRequestLabels: Codable {

    public var id: Int?
    public var nodeId: String?
    public var url: String?
    public var name: String?
    public var description: String?
    public var color: String?
    public var _default: Bool?

    public init(id: Int? = nil, nodeId: String? = nil, url: String? = nil, name: String? = nil, description: String? = nil, color: String? = nil, _default: Bool? = nil) {
        self.id = id
        self.nodeId = nodeId
        self.url = url
        self.name = name
        self.description = description
        self.color = color
        self._default = _default
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case nodeId = "node_id"
        case url
        case name
        case description
        case color
        case _default = "default"
    }

}

