//
// PullRequestMinimalHeadRepo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PullRequestMinimalHeadRepo: Codable {

    public var id: Int
    public var url: String
    public var name: String

    public init(id: Int, url: String, name: String) {
        self.id = id
        self.url = url
        self.name = name
    }

}

