//
// PullRequestReviewCommentLinks.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PullRequestReviewCommentLinks: Codable {

    public var _self: PullRequestReviewCommentLinksSelf
    public var html: PullRequestReviewCommentLinksHtml
    public var pullRequest: PullRequestReviewCommentLinksPullRequest

    public init(_self: PullRequestReviewCommentLinksSelf, html: PullRequestReviewCommentLinksHtml, pullRequest: PullRequestReviewCommentLinksPullRequest) {
        self._self = _self
        self.html = html
        self.pullRequest = pullRequest
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case _self = "self"
        case html
        case pullRequest = "pull_request"
    }

}

