//
// PullRequestMinimal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PullRequestMinimal: Codable {

    public var id: Int
    public var number: Int
    public var url: String
    public var head: PullRequestMinimalHead
    public var base: PullRequestMinimalHead

    public init(id: Int, number: Int, url: String, head: PullRequestMinimalHead, base: PullRequestMinimalHead) {
        self.id = id
        self.number = number
        self.url = url
        self.head = head
        self.base = base
    }

}

