//
// PullRequestMinimalHead.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PullRequestMinimalHead: Codable {

    public var ref: String
    public var sha: String
    public var repo: PullRequestMinimalHeadRepo

    public init(ref: String, sha: String, repo: PullRequestMinimalHeadRepo) {
        self.ref = ref
        self.sha = sha
        self.repo = repo
    }

}

