//
// RateLimit.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RateLimit: Codable {

    public var limit: Int
    public var remaining: Int
    public var reset: Int

    public init(limit: Int, remaining: Int, reset: Int) {
        self.limit = limit
        self.remaining = remaining
        self.reset = reset
    }

}

