//
// Reaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Reactions to conversations provide a way to help people express their feelings more simply and effectively. */
public struct Reaction: Codable {

    public enum Content: String, Codable, CaseIterable {
        case plusOne = "+1"
        case minusOne = "-1"
        case laugh = "laugh"
        case confused = "confused"
        case heart = "heart"
        case hooray = "hooray"
        case rocket = "rocket"
        case eyes = "eyes"
    }
    public var id: Int
    public var nodeId: String
    public var user: SimpleUser?
    /** The reaction to use */
    public var content: Content
    public var createdAt: Date

    public init(id: Int, nodeId: String, user: SimpleUser?, content: Content, createdAt: Date) {
        self.id = id
        self.nodeId = nodeId
        self.user = user
        self.content = content
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case nodeId = "node_id"
        case user
        case content
        case createdAt = "created_at"
    }

}

