//
// ReposOwnerRepoGitCommitsCommitter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Information about the person who is making the commit. By default, &#x60;committer&#x60; will use the information set in &#x60;author&#x60;. See the &#x60;author&#x60; and &#x60;committer&#x60; object below for details. */
public struct ReposOwnerRepoGitCommitsCommitter: Codable {

    /** The name of the author (or committer) of the commit */
    public var name: String?
    /** The email of the author (or committer) of the commit */
    public var email: String?
    /** Indicates when this commit was authored (or committed). This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: &#x60;YYYY-MM-DDTHH:MM:SSZ&#x60;. */
    public var date: String?

    public init(name: String? = nil, email: String? = nil, date: String? = nil) {
        self.name = name
        self.email = email
        self.date = date
    }

}

