//
// ReposOwnerRepoGitTagsTagger.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** An object with information about the individual creating the tag. */
public struct ReposOwnerRepoGitTagsTagger: Codable {

    /** The name of the author of the tag */
    public var name: String?
    /** The email of the author of the tag */
    public var email: String?
    /** When this object was tagged. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: &#x60;YYYY-MM-DDTHH:MM:SSZ&#x60;. */
    public var date: String?

    public init(name: String? = nil, email: String? = nil, date: String? = nil) {
        self.name = name
        self.email = email
        self.date = date
    }

}

