//
// ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviews.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Require at least one approving review on a pull request, before merging. Set to &#x60;null&#x60; to disable. */
public struct ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviews: Codable {

    public var dismissalRestrictions: ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviewsDismissalRestrictions?
    /** Set to &#x60;true&#x60; if you want to automatically dismiss approving reviews when someone pushes a new commit. */
    public var dismissStaleReviews: Bool?
    /** Blocks merging pull requests until [code owners](https://help.github.com/articles/about-code-owners/) review them. */
    public var requireCodeOwnerReviews: Bool?
    /** Specify the number of reviewers required to approve pull requests. Use a number between 1 and 6. */
    public var requiredApprovingReviewCount: Int?

    public init(dismissalRestrictions: ReposOwnerRepoBranchesBranchProtectionRequiredPullRequestReviewsDismissalRestrictions? = nil, dismissStaleReviews: Bool? = nil, requireCodeOwnerReviews: Bool? = nil, requiredApprovingReviewCount: Int? = nil) {
        self.dismissalRestrictions = dismissalRestrictions
        self.dismissStaleReviews = dismissStaleReviews
        self.requireCodeOwnerReviews = requireCodeOwnerReviews
        self.requiredApprovingReviewCount = requiredApprovingReviewCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case dismissalRestrictions = "dismissal_restrictions"
        case dismissStaleReviews = "dismiss_stale_reviews"
        case requireCodeOwnerReviews = "require_code_owner_reviews"
        case requiredApprovingReviewCount = "required_approving_review_count"
    }

}

