//
// ReposOwnerRepoPullsPullNumberReviewsComments.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ReposOwnerRepoPullsPullNumberReviewsComments: Codable {

    /** The relative path to the file that necessitates a review comment. */
    public var path: String
    /** The position in the diff where you want to add a review comment. Note this value is not the same as the line number in the file. For help finding the position value, read the note below. */
    public var position: Int?
    /** Text of the review comment. */
    public var body: String
    public var line: Int?
    public var side: String?
    public var startLine: Int?
    public var startSide: String?

    public init(path: String, position: Int? = nil, body: String, line: Int? = nil, side: String? = nil, startLine: Int? = nil, startSide: String? = nil) {
        self.path = path
        self.position = position
        self.body = body
        self.line = line
        self.side = side
        self.startLine = startLine
        self.startSide = startSide
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case path
        case position
        case body
        case line
        case side
        case startLine = "start_line"
        case startSide = "start_side"
    }

}

