//
// RepositorySubscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Repository invitations let you manage who you collaborate with. */
public struct RepositorySubscription: Codable {

    /** Determines if notifications should be received from this repository. */
    public var subscribed: Bool
    /** Determines if all notifications should be blocked from this repository. */
    public var ignored: Bool
    public var reason: String?
    public var createdAt: Date
    public var url: String
    public var repositoryUrl: String

    public init(subscribed: Bool, ignored: Bool, reason: String?, createdAt: Date, url: String, repositoryUrl: String) {
        self.subscribed = subscribed
        self.ignored = ignored
        self.reason = reason
        self.createdAt = createdAt
        self.url = url
        self.repositoryUrl = repositoryUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case subscribed
        case ignored
        case reason
        case createdAt = "created_at"
        case url
        case repositoryUrl = "repository_url"
    }

}

