//
// ReposOwnerRepoContentsPathCommitter.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The person that committed the file. Default: the authenticated user. */
public struct ReposOwnerRepoContentsPathCommitter: Codable {

    /** The name of the author or committer of the commit. You&#39;ll receive a &#x60;422&#x60; status code if &#x60;name&#x60; is omitted. */
    public var name: String
    /** The email of the author or committer of the commit. You&#39;ll receive a &#x60;422&#x60; status code if &#x60;email&#x60; is omitted. */
    public var email: String
    public var date: String?

    public init(name: String, email: String, date: String? = nil) {
        self.name = name
        self.email = email
        self.date = date
    }

}

