//
// RunnerLabels.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RunnerLabels: Codable {

    public enum ModelType: String, Codable, CaseIterable {
        case readOnly = "read-only"
        case custom = "custom"
    }
    /** Unique identifier of the label. */
    public var id: Int?
    /** Name of the label. */
    public var name: String?
    /** The type of label. Read-only labels are applied automatically when the runner is configured. */
    public var type: ModelType?

    public init(id: Int? = nil, name: String? = nil, type: ModelType? = nil) {
        self.id = id
        self.name = name
        self.type = type
    }

}

