//
// RunnerGroupsOrg.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct RunnerGroupsOrg: Codable {

    public var id: Double
    public var name: String
    public var visibility: String
    public var _default: Bool
    /** Link to the selected repositories resource for this runner group. Not present unless visibility was set to &#x60;selected&#x60; */
    public var selectedRepositoriesUrl: String?
    public var runnersUrl: String
    public var inherited: Bool
    public var inheritedAllowsPublicRepositories: Bool?
    public var allowsPublicRepositories: Bool

    public init(id: Double, name: String, visibility: String, _default: Bool, selectedRepositoriesUrl: String? = nil, runnersUrl: String, inherited: Bool, inheritedAllowsPublicRepositories: Bool? = nil, allowsPublicRepositories: Bool) {
        self.id = id
        self.name = name
        self.visibility = visibility
        self._default = _default
        self.selectedRepositoriesUrl = selectedRepositoriesUrl
        self.runnersUrl = runnersUrl
        self.inherited = inherited
        self.inheritedAllowsPublicRepositories = inheritedAllowsPublicRepositories
        self.allowsPublicRepositories = allowsPublicRepositories
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id
        case name
        case visibility
        case _default = "default"
        case selectedRepositoriesUrl = "selected_repositories_url"
        case runnersUrl = "runners_url"
        case inherited
        case inheritedAllowsPublicRepositories = "inherited_allows_public_repositories"
        case allowsPublicRepositories = "allows_public_repositories"
    }

}

