//
// ScimError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Scim Error */
public struct ScimError: Codable {

    public var message: String?
    public var documentationUrl: String?
    public var detail: String?
    public var status: Int?
    public var scimType: String?
    public var schemas: [String]?

    public init(message: String? = nil, documentationUrl: String? = nil, detail: String? = nil, status: Int? = nil, scimType: String? = nil, schemas: [String]? = nil) {
        self.message = message
        self.documentationUrl = documentationUrl
        self.detail = detail
        self.status = status
        self.scimType = scimType
        self.schemas = schemas
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case message
        case documentationUrl = "documentation_url"
        case detail
        case status
        case scimType
        case schemas
    }

}

