//
// ScopedInstallation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct ScopedInstallation: Codable {

    public enum RepositorySelection: String, Codable, CaseIterable {
        case all = "all"
        case selected = "selected"
    }
    public var permissions: AppPermissions
    /** Describe whether all repositories have been selected or there&#39;s a selection involved */
    public var repositorySelection: RepositorySelection
    public var singleFileName: String?
    public var hasMultipleSingleFiles: Bool?
    public var singleFilePaths: [String]?
    public var repositoriesUrl: String
    public var account: SimpleUser?

    public init(permissions: AppPermissions, repositorySelection: RepositorySelection, singleFileName: String?, hasMultipleSingleFiles: Bool? = nil, singleFilePaths: [String]? = nil, repositoriesUrl: String, account: SimpleUser?) {
        self.permissions = permissions
        self.repositorySelection = repositorySelection
        self.singleFileName = singleFileName
        self.hasMultipleSingleFiles = hasMultipleSingleFiles
        self.singleFilePaths = singleFilePaths
        self.repositoriesUrl = repositoriesUrl
        self.account = account
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case permissions
        case repositorySelection = "repository_selection"
        case singleFileName = "single_file_name"
        case hasMultipleSingleFiles = "has_multiple_single_files"
        case singleFilePaths = "single_file_paths"
        case repositoriesUrl = "repositories_url"
        case account
    }

}

