//
// SelectedActions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SelectedActions: Codable {

    /** Whether GitHub-owned actions are allowed. For example, this includes the actions in the &#x60;actions&#x60; organization. */
    public var githubOwnedAllowed: Bool
    /** Specifies a list of string-matching patterns to allow specific action(s). Wildcards, tags, and SHAs are allowed. For example, &#x60;monalisa/octocat@*&#x60;, &#x60;monalisa/octocat@v2&#x60;, &#x60;monalisa/_*&#x60;.\&quot; */
    public var patternsAllowed: [String]

    public init(githubOwnedAllowed: Bool, patternsAllowed: [String]) {
        self.githubOwnedAllowed = githubOwnedAllowed
        self.patternsAllowed = patternsAllowed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case githubOwnedAllowed = "github_owned_allowed"
        case patternsAllowed = "patterns_allowed"
    }

}

