//
// ShortBlob.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Short Blob */
public struct ShortBlob: Codable {

    public var url: String
    public var sha: String

    public init(url: String, sha: String) {
        self.url = url
        self.sha = sha
    }

}

