//
// Status.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** The status of a commit. */
public struct Status: Codable {

    public var url: String
    public var avatarUrl: String?
    public var id: Int
    public var nodeId: String
    public var state: String
    public var description: String
    public var targetUrl: String
    public var context: String
    public var createdAt: String
    public var updatedAt: String
    public var creator: SimpleUser?

    public init(url: String, avatarUrl: String?, id: Int, nodeId: String, state: String, description: String, targetUrl: String, context: String, createdAt: String, updatedAt: String, creator: SimpleUser?) {
        self.url = url
        self.avatarUrl = avatarUrl
        self.id = id
        self.nodeId = nodeId
        self.state = state
        self.description = description
        self.targetUrl = targetUrl
        self.context = context
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.creator = creator
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case url
        case avatarUrl = "avatar_url"
        case id
        case nodeId = "node_id"
        case state
        case description
        case targetUrl = "target_url"
        case context
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case creator
    }

}

