//
// Tag.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Tag */
public struct Tag: Codable {

    public var name: String
    public var commit: ShortBranchCommit
    public var zipballUrl: String
    public var tarballUrl: String
    public var nodeId: String

    public init(name: String, commit: ShortBranchCommit, zipballUrl: String, tarballUrl: String, nodeId: String) {
        self.name = name
        self.commit = commit
        self.zipballUrl = zipballUrl
        self.tarballUrl = tarballUrl
        self.nodeId = nodeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case commit
        case zipballUrl = "zipball_url"
        case tarballUrl = "tarball_url"
        case nodeId = "node_id"
    }

}

