//
// TeamProject.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** A team&#39;s access to a project. */
public struct TeamProject: Codable {

    public var ownerUrl: String
    public var url: String
    public var htmlUrl: String
    public var columnsUrl: String
    public var id: Int
    public var nodeId: String
    public var name: String
    public var body: String?
    public var number: Int
    public var state: String
    public var creator: SimpleUser?
    public var createdAt: String
    public var updatedAt: String
    /** The organization permission for this project. Only present when owner is an organization. */
    public var organizationPermission: String?
    /** Whether the project is private or not. Only present when owner is an organization. */
    public var _private: Bool?
    public var permissions: TeamProjectPermissions

    public init(ownerUrl: String, url: String, htmlUrl: String, columnsUrl: String, id: Int, nodeId: String, name: String, body: String?, number: Int, state: String, creator: SimpleUser?, createdAt: String, updatedAt: String, organizationPermission: String? = nil, _private: Bool? = nil, permissions: TeamProjectPermissions) {
        self.ownerUrl = ownerUrl
        self.url = url
        self.htmlUrl = htmlUrl
        self.columnsUrl = columnsUrl
        self.id = id
        self.nodeId = nodeId
        self.name = name
        self.body = body
        self.number = number
        self.state = state
        self.creator = creator
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.organizationPermission = organizationPermission
        self._private = _private
        self.permissions = permissions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case ownerUrl = "owner_url"
        case url
        case htmlUrl = "html_url"
        case columnsUrl = "columns_url"
        case id
        case nodeId = "node_id"
        case name
        case body
        case number
        case state
        case creator
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case organizationPermission = "organization_permission"
        case _private = "private"
        case permissions
    }

}

