//
// TopicSearchResultItemRelated.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TopicSearchResultItemRelated: Codable {

    public var topicRelation: TopicSearchResultItemTopicRelation?

    public init(topicRelation: TopicSearchResultItemTopicRelation? = nil) {
        self.topicRelation = topicRelation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case topicRelation = "topic_relation"
    }

}

