//
// UserSearchResultItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** User Search Result Item */
public struct UserSearchResultItem: Codable {

    public var login: String
    public var id: Int
    public var nodeId: String
    public var avatarUrl: String
    public var gravatarId: String?
    public var url: String
    public var htmlUrl: String
    public var followersUrl: String
    public var subscriptionsUrl: String
    public var organizationsUrl: String
    public var reposUrl: String
    public var receivedEventsUrl: String
    public var type: String
    public var score: Int
    public var followingUrl: String
    public var gistsUrl: String
    public var starredUrl: String
    public var eventsUrl: String
    public var publicRepos: Int?
    public var publicGists: Int?
    public var followers: Int?
    public var following: Int?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var name: String?
    public var bio: String?
    public var email: String?
    public var location: String?
    public var siteAdmin: Bool
    public var hireable: Bool?
    public var textMatches: [Any]?
    public var blog: String?
    public var company: String?
    public var suspendedAt: Date?

    public init(login: String, id: Int, nodeId: String, avatarUrl: String, gravatarId: String?, url: String, htmlUrl: String, followersUrl: String, subscriptionsUrl: String, organizationsUrl: String, reposUrl: String, receivedEventsUrl: String, type: String, score: Int, followingUrl: String, gistsUrl: String, starredUrl: String, eventsUrl: String, publicRepos: Int? = nil, publicGists: Int? = nil, followers: Int? = nil, following: Int? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, name: String? = nil, bio: String? = nil, email: String? = nil, location: String? = nil, siteAdmin: Bool, hireable: Bool? = nil, textMatches: [Any]? = nil, blog: String? = nil, company: String? = nil, suspendedAt: Date? = nil) {
        self.login = login
        self.id = id
        self.nodeId = nodeId
        self.avatarUrl = avatarUrl
        self.gravatarId = gravatarId
        self.url = url
        self.htmlUrl = htmlUrl
        self.followersUrl = followersUrl
        self.subscriptionsUrl = subscriptionsUrl
        self.organizationsUrl = organizationsUrl
        self.reposUrl = reposUrl
        self.receivedEventsUrl = receivedEventsUrl
        self.type = type
        self.score = score
        self.followingUrl = followingUrl
        self.gistsUrl = gistsUrl
        self.starredUrl = starredUrl
        self.eventsUrl = eventsUrl
        self.publicRepos = publicRepos
        self.publicGists = publicGists
        self.followers = followers
        self.following = following
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.name = name
        self.bio = bio
        self.email = email
        self.location = location
        self.siteAdmin = siteAdmin
        self.hireable = hireable
        self.textMatches = textMatches
        self.blog = blog
        self.company = company
        self.suspendedAt = suspendedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case login
        case id
        case nodeId = "node_id"
        case avatarUrl = "avatar_url"
        case gravatarId = "gravatar_id"
        case url
        case htmlUrl = "html_url"
        case followersUrl = "followers_url"
        case subscriptionsUrl = "subscriptions_url"
        case organizationsUrl = "organizations_url"
        case reposUrl = "repos_url"
        case receivedEventsUrl = "received_events_url"
        case type
        case score
        case followingUrl = "following_url"
        case gistsUrl = "gists_url"
        case starredUrl = "starred_url"
        case eventsUrl = "events_url"
        case publicRepos = "public_repos"
        case publicGists = "public_gists"
        case followers
        case following
        case createdAt = "created_at"
        case updatedAt = "updated_at"
        case name
        case bio
        case email
        case location
        case siteAdmin = "site_admin"
        case hireable
        case textMatches = "text_matches"
        case blog
        case company
        case suspendedAt = "suspended_at"
    }

}

