//
// ValidationError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Validation Error */
public struct ValidationError: Codable {

    public var message: String
    public var documentationUrl: String
    public var errors: [ValidationErrorErrors]?

    public init(message: String, documentationUrl: String, errors: [ValidationErrorErrors]? = nil) {
        self.message = message
        self.documentationUrl = documentationUrl
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case message
        case documentationUrl = "documentation_url"
        case errors
    }

}

